title: chrisaitchison.com
url:   http://www.chrisaitchison.com
author:
  name:    Chris Aitchison
  email:   cmaitchison@gmail.com 
  open_id:                 
      - https://www.google.com/accounts/o8/id?id=AItOawnN18ZWmdwfBGRRWyM5xCwO4a5cD0nRnC0

# Delete the following section if your site will not be acting as an OpenID delegate (http://wiki.openid.net/Delegation)
# If you're deploying with mongrel, make sure you read http://rhnh.net/2008/04/13/nginx-openid-delegation-and-yadis
#open_id_delegation:
#  server:   http://www.myopenid.com/server
#  delegate: http://username.myopenid.com
